version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
