BEGIN;

ALTER TABLE exercise ADD COLUMN "type" TEXT NOT NULL;

ALTER TABLE exercise ADD COLUMN prompt TEXT;
ALTER TABLE exercise ADD COLUMN options TEXT[];
ALTER TABLE exercise ADD COLUMN correct_answer TEXT;

COMMIT;