BEGIN;

ALTER TABLE exercise ADD COLUMN "type" TEXT NOT NULL;

ALTER TABLE exercise ADD COLUMN question TEXT;
ALTER TABLE exercise ADD COLUMN options TEXT[];
ALTER TABLE exercise ADD COLUMN answer TEXT;

COMMIT;